completed javascript-operators-and-expressions
Ortiz-Andrew/c-0823-code-solutions pull request #2
Opened 2023-08-28 22:10 UTC by Ortiz-Andrew

![Screenshot 2023-08-28 at 3 07 21 PM](https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/15ce88aa-33ba-4d59-8d02-3812e65e5409)

2023-08-28 23:35 UTC, shawnkost requested changes
Few changes here Andrew!

2023-08-28 23:35 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +const change = bill - payment;
This should be swapped! You should pay more than the bill, otherwise you won't cover your tab 😉

2023-08-28 23:35 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +const grade = quizzes + midterm + final;
After you add all these together, you need to divide them by 3

2023-08-28 23:35 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +const isSparta = true;
Rather than assigning `true` to `isSparta`, you should be assigning it an expression of `headCount === 300`

2023-08-28 23:35 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +let motto = `${firstName}${lastName}`;
You should give motto an initial value of `fullName`, and then using the `+=` operator, you should add a string `' is the Goat` to combine and reassign it back to `motto`

2023-08-29 02:04 UTC, Ortiz-Andrew commented
<img width="468" alt="Screenshot 2023-08-28 at 7 00 48 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/9dcf94d3-8f83-4982-91b5-7b324ea14eee">

2023-08-29 17:03 UTC, shawnkost requested changes
Couple changes here still!

2023-08-29 17:03 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +const change = bill - payment;
These still need to be swapped. It should be `payment - bill`

2023-08-29 17:03 UTC, shawnkost commented on javascript-operators-and-expressions/main.js
> +let motto = `${firstName}${lastName}`;
This still needs to be updated. You should initialize `motto` to a value of `fullName`, but then using the `+=` operator you add a string, like what you're doing on line 31. You're more than welcome to use template literals in the future, but for this exercise, you need to do the `+=`

2023-09-05 22:24 UTC, Ortiz-Andrew commented
fixed

2023-09-06 17:05 UTC, shawnkost approved these changes
👍🏻

2023-09-07 18:28 UTC, merged