Css layout classes
Ortiz-Andrew/c-0823-code-solutions pull request #31
Opened 2023-09-08 03:42 UTC by Ortiz-Andrew

<img width="879" alt="Screenshot 2023-09-07 at 8 39 02 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/79408bdd-f7fa-4bd9-963c-36c46ae85ac7">
<img width="885" alt="Screenshot 2023-09-07 at 8 39 13 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/697b5648-f58a-49ef-948c-3352d7e6312e">

2023-09-08 16:38 UTC, shawnkost requested changes
Some changes here Andrew! Make sure you are comparing your structure to the snippet we provided in the instructions. Your class names should follow the same structure. `.row` is where `display: flex` gets applied, and the direct children will be your columns, with names such as `column-third`, `column-two-thirds` etc.

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/index.html
> +        <p class="column-third">
These shouldn't have a `column-third` class. They are inside of your `column-third`, they aren't a new column

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          </div>
Everything should not be inside of your `two-thirds` class. You should have 2 sibling elements, one with a `column-third` & another one with a `column-two-thirds`

`.row` > `.column-third` & `.column-two-thirds`. And then your content for the columns would go inside their respective column

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/index.html
> +          </div>
Same note as above ^

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +  width: 100%;
This isn't doing anything. You're setting the `width` via your `flex-basis`

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +  flex-wrap: nowrap;
`flex-wrap` is a parent property, which means it gets applied where `display: flex` gets applied, so this isn't doing anything and should be deleted

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +  flex-basis: auto;
This `flex-basis` isn't doing anything because it's parent isn't a flex parent, so this should be deleted

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
You shouldn't need to give this a `height`, and you already have a `characters` class where you're applying the `width: 100%`, so you should just delete this selector and give the `img` the `characters` class instead

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
`.par1-2` isn't descriptive. Is this supposed to be a row? A column? I would delete this completely. Your class names should follow the structure in the instructions. `.row` or `column` classes

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
Your `column` classes shouldn't have `display: flex` here

2023-09-08 16:38 UTC, shawnkost commented on css-layout-classes/styles.css
> +}
You shouldn't be setting a `px` width on your `image` and you shouldn't be setting a `height`. You should just give this `img` the characters class

2023-09-09 20:37 UTC, Ortiz-Andrew commented
<img width="976" alt="Screenshot 2023-09-09 at 1 35 59 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/3614da73-f890-4449-aa8f-4c3120767513">

2023-09-09 20:37 UTC, Ortiz-Andrew commented
<img width="911" alt="Screenshot 2023-09-09 at 1 28 18 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/6729c6fc-179b-4cf0-9699-6309e31ab404">

2023-09-11 16:10 UTC, shawnkost requested changes
👍🏻

2023-09-11 16:11 UTC, shawnkost approved these changes
👍🏻

2023-09-11 17:11 UTC, merged