the best i can do
Ortiz-Andrew/c-0823-code-solutions pull request #32
Opened 2023-09-08 07:17 UTC by Ortiz-Andrew

<img width="1216" alt="Screenshot 2023-09-08 at 12 09 23 AM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/d6ff3c3d-05fe-49a7-9868-b436b251a8e3">

2023-09-08 17:05 UTC, shawnkost requested changes
Doesn't quite look like the example image Andrew! You need to try to get it as close as possible to the example image. If you are struggling to get that to happen, then you need to make sure to reach out and ask questions, but you can't just turn this in. It should be so close that I can barely notice differences.

For example, the images are being cut off and not showing correctly. Your heading text isn't centered like the example image. It's important that you try and replicate your example image as close as possible, becuase this is what's expected from you on the job. If you need help, then reach out!

2023-09-08 17:05 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-basis: 20%;
`width` & `flex-basis` are essentially the same thing (with some caveats). You should not be setting both. You should be using `flex-basis` to essentally set the `width`

2023-09-08 17:05 UTC, shawnkost commented on css-three-column-layout/styles.css
> +  flex-basis: calc(100% / 3);
`width` & `flex-basis` are essentially the same thing (with some caveats). You should not be setting both. You should be using `flex-basis` to essentally set the `width`

2023-09-10 02:29 UTC, Ortiz-Andrew commented
<img width="1087" alt="Screenshot 2023-09-09 at 7 21 33 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/8c409238-0801-402f-a694-4664af2ab63e">

2023-09-11 16:24 UTC, shawnkost approved these changes
👍🏻

2023-09-13 18:28 UTC, merged