completed javascript-conditionals
Ortiz-Andrew/c-0823-code-solutions pull request #9
Opened 2023-08-30 21:47 UTC by Ortiz-Andrew

![Screenshot 2023-08-30 at 2 46 29 PM](https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/ffc6463b-38ee-4dbc-b5e9-7f9d74cc1960)

2023-08-30 21:57 UTC, shawnkost requested changes
Some changes here Andrew!

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  Age: 27,
property names should be lowercase

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  if (person >= 21) {
You should be checking the `age` property of the `person` object

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +    return false;
If they are 21 or older that means they are old enough to drink, so this should be `return true`

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  if (person >= 16) {
You should be checking the `age` property of the `person` object

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +}
If the person is 16 or older, that means they are old enough to drive, so you should be `return true`

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  if (person < 21) {
You should be checking the `age` property of the `person` object

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +}
Drinking & driving is illegal, so you should only be `return false`

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > 7) {
This should be greater than or equal to 0 & less than 7

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH < 7 || pH < 14) {
This should be greater than 7 or less than or equal to 14

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > -1) {
This shouldn't have any conditional. This should just be an `else`

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +console.log('introduce Warner Bros: ', introduceWarnerBro(name));
You should be passing in a string when you call the function, like `'wakko'`

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +      return 'Genre not recognized. Choose between action, comedy, horror, drama, musical, or scifi';
This should actually be your `default` clause, and you shouldn't have a `random` clause

2023-08-30 21:57 UTC, shawnkost commented on javascript-conditionals/main.js
> +console.log('recommened movies:', recommendMovie(genre));
You should be passing in a string for whatever genre you want, not passing in a whole object

2023-08-31 03:15 UTC, Ortiz-Andrew commented
<img width="422" alt="Screenshot 2023-08-30 at 8 12 01 PM" src="https://github.com/Ortiz-Andrew/c-0823-code-solutions/assets/136508122/6fd7641f-3d5b-4589-9495-28de15dfb96c">

2023-08-31 15:27 UTC, shawnkost requested changes
Just a couple more tweaks!

2023-08-31 15:27 UTC, shawnkost commented on javascript-conditionals/main.js
> +    return true;
This should be `return false`. We only want to `return false` from this function

2023-08-31 15:27 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > 7 && pH >= 0) {
This should be less than 7

2023-09-05 22:31 UTC, Ortiz-Andrew commented
fixed

2023-09-06 17:07 UTC, shawnkost requested changes
Couple changes here!

2023-09-06 17:07 UTC, shawnkost commented on javascript-conditionals/main.js
>    } else if (pH > 7 && pH >= 0) {
This should be less than 7

2023-09-06 17:07 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > 7 && pH < 7) {
This should still be `<= 14`

2023-09-07 15:25 UTC, shawnkost approved these changes
👍🏻

2023-09-07 18:30 UTC, merged